language: node_js

node_js:
  - 10
  - 12

cache: npm

install: npm ci

before_script:
  - npm install -g npm
  - npm install -g gulp

jobs:
  include:
    - stage: Lint
      script: gulp lint
    - stage: Build
      before_script:
        - npm install -g greenkeeper-lockfile
        - greenkeeper-lockfile-update
      script: gulp build
      after_script:
        - greenkeeper-lockfile-upload
    - stage: Test
      name: Unit Tests
      script: gulp test
    - stage: Coverage
      name: Test Coverage
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: gulp coverage
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: Deploy
      deploy:
        provider: script
        script: gulp distribute
        skip_cleanup: true
