import SemanticReleaseError from '@semantic-release/error';

const packageName = process.env.COLONISE_PACKAGE_NAME;

if (!packageName) {
    throw new SemanticReleaseError(
        'The package name must be provided.',
        'ENOPACKAGENAME',
        `Make sure to add the environment variable 'COLONISE_PACKAGE_NAME' to the Travis CI build.`
    );
}

const packageNameLower = packageName.toLowerCase();

const changelog = {
    path: '@semantic-release/changelog',
    changelogFile: 'CHANGELOG.md',
    changelogTitle: 'Changelog'
};

const git = {
    path: '@semantic-release/git'
};

const github = {
    path: '@semantic-release/github',
    successComment: `This \${issue.pull_request ? 'pull request has been included in' : 'issue has been resolved in'} **[release \${nextRelease.gitTag}](https://github.com/Colonise/${packageName}/releases/tag/\${nextRelease.gitTag})**!

You can install the **[npm package](https://www.npmjs.com/package/@colonise/${packageNameLower})** for \${nextRelease.gitTag} using \`npm install @colonise/${packageNameLower}@\${nextRelease.version}\`

_Automatically generated by [semantic-release](https://github.com/semantic-release/semantic-release)._`,
    failTitle: `The automatic publishing of release \${nextRelease.gitTag} is failing.`
};

const npm = {
    path: '@semantic-release/npm'
};

export const plugins = [
    changelog,
    git,
    github,
    npm
];
